import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:1200,height:820}});let errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto('http://127.0.0.1:5173/IntroGenerator/');await page.waitForFunction(()=>window.__IG?.state?.compiled&&window.__IG.state.p.format==='IGAUTHOR/1.4',{timeout:60000});
 const initialStored=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('IntroGenerator',1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const p=await new Promise((resolve,reject)=>{const r=db.transaction('projects').objectStore('projects').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return{format:p?.format,eases:p?.tracks.flatMap(t=>t.keys).map(k=>k.ease?.kind)||[]}});if(initialStored.format!=='IGAUTHOR/1.4'||initialStored.eases.some(x=>x!=='stack'))throw Error('new project/animate did not persist direct IGAUTHOR/1.4 stacks: '+JSON.stringify(initialStored));
 const keyButton=page.locator('.key-button.on').first();if(!await keyButton.count())throw Error('animated keyframe control not found');await keyButton.click();await page.waitForFunction(()=>document.querySelector('#dialog-title')?.textContent.includes('キーフレーム'));await page.waitForTimeout(500);if(!await page.locator('.easing-stack-editor').count()){const diagnostic=await page.evaluate(()=>{const s=window.__IG.state,rows=[...document.querySelectorAll('#keys > tr')].filter(r=>r.querySelector('select[aria-label="Easing"]')),root=s.p.nodes.find(n=>n.id===s.id),exps=new Map(s.p.expressions.map(e=>[e.id,e])),refs=new Set(),seen=new Set();const walk=v=>{if(!v||typeof v!=='object'||seen.has(v))return;seen.add(v);if(typeof v.expr==='string'){const e=exps.get(v.expr);if(e?.op==='track')refs.add(e.track)}for(const x of Array.isArray(v)?v:Object.values(v))walk(x)};walk(root);const near=(a,b)=>Math.abs(a-b)<1e-6,candidates=s.p.tracks.filter(t=>!refs.size||refs.has(t.id)).filter(tr=>tr.keys.length===rows.length&&rows.every((r,i)=>{const k=tr.keys[i],a=s.p.timeAnchors.find(a=>a.target==='keyframe'&&a.owner===tr.id&&a.key===k.id),time=r.querySelector('input[aria-label="Key位置"]'),value=r.querySelector('input[aria-label="Key値"]'),unit=r.querySelector('select[aria-label="時間単位"]');return time&&value&&unit&&near(Number(time.value),a?.value??k.time)&&near(Number(value.value),k.value)&&unit.value===(a?.unit||'seconds')}));return{selected:s.id,title:document.querySelector('#dialog-title')?.textContent,format:s.p.format,refs:[...refs],rows:rows.map(r=>({time:r.querySelector('input[aria-label="Key位置"]')?.value,value:r.querySelector('input[aria-label="Key値"]')?.value,unit:r.querySelector('select[aria-label="時間単位"]')?.value,easing:r.querySelector('select[aria-label="Easing"]')?.value})),tracks:s.p.tracks.filter(t=>refs.has(t.id)).map(t=>({id:t.id,keys:t.keys.map(k=>({time:k.time,value:k.value,ease:k.ease?.kind}))})),candidates:candidates.map(t=>t.id)}});throw Error('Easing Stack editor did not mount: '+JSON.stringify(diagnostic))}
 const editor=page.locator('.easing-stack-editor').first(),row=editor.locator('xpath=ancestor::tr[1]');const before={time:await row.locator('input[aria-label="Key位置"]').inputValue(),value:await row.locator('input[aria-label="Key値"]').inputValue()};
 const layer=async i=>editor.locator('.easing-layer').nth(i);
 let l=await layer(0);await l.locator('select[aria-label$="Easing種類"]').selectOption('power');await l.locator('select[aria-label$="Easing方向"]').selectOption('InOut');let weight=l.locator('input[aria-label$="Weight"]');await weight.fill('0.6');await weight.press('Tab');await page.waitForFunction(()=>window.__IG.state.p.tracks.some(t=>t.keys.some(k=>k.ease?.kind==='stack'&&k.ease.layers.some(l=>l.curve.kind==='powerInOut'&&Math.abs(l.weight-.6)<1e-9))),{timeout:15000});
 await editor.locator('button[aria-label="Easing Layerを追加"]').click();await page.waitForFunction(()=>document.querySelector('.easing-stack-editor')?.querySelectorAll('.easing-layer').length>=2);l=await layer(1);await l.locator('select[aria-label$="Easing種類"]').selectOption('back');await l.locator('select[aria-label$="Easing方向"]').selectOption('Out');weight=l.locator('input[aria-label$="Weight"]');await weight.fill('0.25');await weight.press('Tab');let over=l.locator('input[aria-label$="Easing Overshoot"]');await over.fill('2.4');await over.press('Tab');
 await editor.locator('button[aria-label="Easing Layerを追加"]').click();await page.waitForFunction(()=>document.querySelector('.easing-stack-editor')?.querySelectorAll('.easing-layer').length>=3);l=await layer(2);await l.locator('select[aria-label$="Easing種類"]').selectOption('elastic');await l.locator('select[aria-label$="Easing方向"]').selectOption('Out');weight=l.locator('input[aria-label$="Weight"]');await weight.fill('0.1');await weight.press('Tab');let period=l.locator('input[aria-label$="Easing 振動周期"]');await period.fill('0.2');await period.press('Tab');
 await page.waitForFunction(()=>window.__IG.state.p.tracks.some(t=>t.keys.some(k=>k.ease?.layers?.length>=3&&k.ease.layers.some(l=>l.curve.kind==='backOut'&&Math.abs(l.weight-.25)<1e-9&&Math.abs(l.curve.overshoot-2.4)<1e-9)&&k.ease.layers.some(l=>l.curve.kind==='elasticOut'&&Math.abs(l.weight-.1)<1e-9&&Math.abs(l.curve.period-.2)<1e-9))),{timeout:15000});
 const after={time:await row.locator('input[aria-label="Key位置"]').inputValue(),value:await row.locator('input[aria-label="Key値"]').inputValue()};if(before.time!==after.time||before.value!==after.value)throw Error(`Easing Stack changed key endpoints/time: ${JSON.stringify({before,after})}`);
 const idsBefore=await page.evaluate(()=>window.__IG.state.p.tracks.flatMap(t=>t.keys).find(k=>k.ease?.layers?.length>=3).ease.layers.map(l=>l.id));l=await layer(1);await l.locator('button[aria-label$="を複製"]').click();await page.waitForFunction(()=>document.querySelector('.easing-stack-editor')?.querySelectorAll('.easing-layer').length===4);await page.locator('[data-easing-history="undo"]').click();await page.waitForFunction(()=>document.querySelector('.easing-stack-editor')?.querySelectorAll('.easing-layer').length===3);await page.locator('[data-easing-history="redo"]').click();await page.waitForFunction(()=>document.querySelector('.easing-stack-editor')?.querySelectorAll('.easing-layer').length===4);
 l=await layer(3);await l.locator('button[aria-label$="を削除"]').click();await page.waitForFunction(()=>document.querySelector('.easing-stack-editor')?.querySelectorAll('.easing-layer').length===3);l=await layer(2);await l.locator('button[aria-label$="を上へ"]').click();await page.waitForFunction(ids=>{const k=window.__IG.state.p.tracks.flatMap(t=>t.keys).find(k=>k.ease?.layers?.length===3);return k&&k.ease.layers[0].id===ids[0]&&k.ease.layers[1].id===ids[2]&&k.ease.layers[2].id===ids[1]},idsBefore);
 const roundtrip=await page.evaluate(async()=>{const s=window.__IG.state,compiled=await window.__IG.compile(structuredClone(s.p)),out=await window.__IG.exportSB3(compiled),back=await window.__IG.importSB3(out.bytes),k=back.source.tracks.flatMap(t=>t.keys).find(k=>k.ease?.layers?.length===3);return{format:back.source.format,ids:k?.ease.layers.map(l=>l.id),weights:k?.ease.layers.map(l=>l.weight)}});if(roundtrip.format!=='IGAUTHOR/1.4'||roundtrip.ids?.length!==3)throw Error('Easing Stack sb3 roundtrip failed');
 const migration=await page.evaluate(async()=>{const p=structuredClone(window.__IG.state.p),k=p.tracks.flatMap(t=>t.keys).find(k=>k.ease?.layers?.length);p.format='IGAUTHOR/1.3';k.ease={kind:'powerInOut',power:3};await window.__IG.compile(p);return{format:p.format,ease:k.ease}});if(migration.format!=='IGAUTHOR/1.4'||migration.ease.kind!=='stack'||migration.ease.layers.length!==1||migration.ease.layers[0].weight!==1||migration.ease.layers[0].curve.kind!=='powerInOut')throw Error('IGAUTHOR/1.3 migration failed');
 const savedIds=await page.evaluate(()=>window.__IG.state.p.tracks.flatMap(t=>t.keys).find(k=>k.ease?.layers?.length===3).ease.layers.map(l=>l.id));await page.reload();await page.waitForFunction(()=>window.__IG?.state?.compiled&&window.__IG.state.p.format==='IGAUTHOR/1.4',{timeout:60000});const reloadedIds=await page.evaluate(()=>window.__IG.state.p.tracks.flatMap(t=>t.keys).find(k=>k.ease?.layers?.length===3)?.ease.layers.map(l=>l.id));if(JSON.stringify(savedIds)!==JSON.stringify(reloadedIds))throw Error('Easing Stack persistence lost layer IDs/order');
 await page.setViewportSize({width:390,height:844});await page.locator('.key-button.on').first().click();await page.waitForSelector('.easing-stack-editor');if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Easing Stack UI causes mobile horizontal overflow');
 if(errors.length)throw Error(errors.join('\n'));console.log({easingStack:'IGAUTHOR/1.4 pass',initialStored,before,after,roundtrip});
}finally{await browser.close()}
