import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage();await page.goto('http://127.0.0.1:5173/IntroGenerator/');await page.waitForFunction(()=>window.__IG,{timeout:60000});await page.waitForSelector('.timing-node-anchor',{timeout:10000});
 await page.click('#project-settings');await page.waitForSelector('#timing-project-panel',{timeout:10000});const timingUi=await page.evaluate(()=>({tempoRows:document.querySelectorAll('.timing-table-row').length,tempoInputs:document.querySelectorAll('#timing-project-panel input[type="number"]').length,nodeUnits:document.querySelectorAll('.timing-node-anchor select').length,legacyBpmHidden:[...document.querySelectorAll('#project-fields > label')].some(x=>x.textContent.trim().startsWith('BPM')&&x.hidden)}));if(timingUi.tempoRows<1||timingUi.tempoInputs<2||timingUi.nodeUnits!==2||!timingUi.legacyBpmHidden)throw Error('timing editor controls are not mounted accessibly: '+JSON.stringify(timingUi));
 await page.getByRole('button',{name:'＋ 現在位置にTempo区間'}).click();await page.waitForFunction(()=>window.__IG.state.p.tempo.length===2);const secondBpm=page.locator('input[aria-label="Tempo 2 BPM"]');await secondBpm.fill('60');await secondBpm.dispatchEvent('change');await page.waitForFunction(()=>window.__IG.state.p.tempo[1]?.bpm===60);await page.click('#dialog-close');
 await page.locator('.layer .name').filter({hasText:'Orbit ring'}).first().click();await page.locator('button[aria-label="回転 °のキーフレーム"]').first().click();await page.waitForFunction(()=>document.querySelector('#dialog-title')?.textContent.includes('キーフレーム'));await page.waitForFunction(()=>document.querySelectorAll('#keys select[aria-label="時間単位"]')[1]?.dataset.timingPatched==='1');const secondUnit=page.locator('#keys select[aria-label="時間単位"]').nth(1);await secondUnit.selectOption('beats');await page.waitForFunction(()=>window.__IG.state.p.timeAnchors.some(a=>a.target==='keyframe'&&a.unit==='beats'&&Math.abs(a.value-7.2)<1e-6));const converted=Number(await page.locator('#keys input[aria-label="Key位置"]').nth(1).inputValue());if(Math.abs(converted-7.2)>1e-6)throw Error('keyframe UI used single-BPM conversion: '+converted);await page.click('#dialog-close');
 await page.setViewportSize({width:390,height:844});await page.locator('.mobile-tabs button[data-pane="layers"]').click();await page.click('#project-settings');await page.waitForSelector('#timing-project-panel');const mobileFit=await page.evaluate(()=>{const d=document.querySelector('#dialog'),p=document.querySelector('#timing-project-panel');return {dialog:d.scrollWidth<=d.clientWidth+1,panel:p.scrollWidth<=p.clientWidth+1,page:document.documentElement.scrollWidth<=innerWidth+1}});if(!mobileFit.dialog||!mobileFit.panel||!mobileFit.page)throw Error('timing UI overflows on mobile: '+JSON.stringify(mobileFit));await page.click('#dialog-close');
 console.log(await page.evaluate(async()=>{
 const {makeProject,node,addNode,solid,syncTiming}=await import('/IntroGenerator/src/model.js');const {compile,validateSource}=await import('/IntroGenerator/src/compiler.js');const {Runtime}=await import('/IntroGenerator/src/runtime.js');const {exportSB3,importSB3}=await import('/IntroGenerator/src/scratch.js');const {encodeWav}=await import('/IntroGenerator/src/audio.js');const {b64,digest}=await import('/IntroGenerator/src/assets.js');
 const check=(x,m)=>{if(!x)throw Error(m)}, project=()=>{const p=makeProject();p.duration=.1;p.nodes.find(n=>n.id===p.root).time.end=.1;p.nodes.find(n=>n.id===p.root).time.duration=.1;p.background=[0,0,0,1];return p}, rectangle=(p,parent)=>{const n=node('shape');n.data.shape='rectangle';n.data.params.width=100;n.data.params.height=100;n.data.paint=solid([1,1,1,1]);addNode(p,n,parent);n.time.end=p.duration;n.time.duration=p.duration;return n}, pixel=(c,x=240,y=180)=>{const canvas=document.createElement('canvas');canvas.width=480;canvas.height=360;new Runtime(c).draw(canvas,0);return canvas.getContext('2d').getImageData(x,y,1,1).data};
 const timing=makeProject();timing.tracks.push({id:'beatTrack',unit:'scalar',default:0,keys:[{id:'beatKey',time:1,value:1,ease:{kind:'linear'}}]},{id:'secondTrack',unit:'scalar',default:0,keys:[{id:'secondKey',time:1,value:1,ease:{kind:'linear'}}]});timing.timeAnchors.push({id:'beatAnchor',target:'keyframe',owner:'beatTrack',key:'beatKey',unit:'beats',value:2},{id:'secondAnchor',target:'keyframe',owner:'secondTrack',key:'secondKey',unit:'seconds',value:1});timing.markers.push({id:'beatMarker',name:'Chorus',unit:'beats',value:2});syncTiming(timing);check(timing.tracks.find(t=>t.id==='beatTrack').keys[0].time===1,'PDF-F08 2 beats should resolve to 1 second at 120 BPM');check(timing.tracks.find(t=>t.id==='secondTrack').keys[0].time===1,'PDF-F08 seconds anchor moved before BPM change');timing.tempo[0].bpm=60;syncTiming(timing);check(timing.tracks.find(t=>t.id==='beatTrack').keys[0].time===2,'PDF-F08 beat-fixed key did not move to 2 seconds');check(timing.tracks.find(t=>t.id==='secondTrack').keys[0].time===1,'PDF-F08 second-fixed key moved');check(timing.markers[0].unit==='beats'&&timing.markers[0].value===2,'PDF-F08 marker unit/value changed');const inconsistent=structuredClone(timing);inconsistent.tracks.find(t=>t.id==='beatTrack').keys[0].time=1;let rejected=false;try{validateSource(inconsistent)}catch{rejected=true}check(rejected,'inconsistent Time Anchor cache was accepted on load');
 const conflict=makeProject(),n=node('shape','Timed');addNode(conflict,n);n.time.end=1;conflict.timeAnchors.push({id:'startAnchor',target:'nodeStart',owner:n.id,key:null,unit:'beats',value:4},{id:'endAnchor',target:'nodeEnd',owner:n.id,key:null,unit:'seconds',value:1});conflict.tempo[0].bpm=60;let rolled=false;try{syncTiming(conflict)}catch{rolled=true}check(rolled,'node start/end inversion was not rejected');
 const a=project(),g=node('group');g.opacityMode='isolated';g.opacity=.5;addNode(a,g);rectangle(a,g.id);rectangle(a,g.id);const ac=await compile(a),center=pixel(ac);check(Math.abs(center[0]-128)<=2,'isolated alpha applied per child: '+center[0]);
 const p=project(),target=rectangle(p),mask=node('shape','mask',null);mask.data.shape='rectangle';mask.data.params.width=50;mask.data.params.height=100;mask.transform.position[0]=25;p.nodes.push(mask);p.definitions.push(mask.id);target.effects=[{id:'maskFx',kind:'mask',source:mask.id,mode:'alpha',invert:false,feather:0}];const mc=await compile(p);check(pixel(mc,215)[0]<3&&pixel(mc,265)[0]>250,'mask coordinate/alpha mismatch');
 target.effects=[{id:'warpFx',kind:'warp',quad:[[-60,-50],[40,-30],[60,50],[-40,30]],sourceRect:[-50,-50,100,100]}];const wc=await compile(p);check(pixel(wc)[0]>250,'warp center missing');check(pixel(wc,320)[0]<3,'warp outside quad filled');
 const vp=project(),world=node('group','world',null);vp.nodes.push(world);vp.definitions.push(world.id);rectangle(vp,world.id);const cam=node('camera');addNode(vp,cam,world.id);for(const rect of [[-240,-180,240,360],[0,-180,240,360]]){const view=node('view');view.data.camera=cam.id;view.data.worldRoot=world.id;view.data.viewport=rect;addNode(vp,view)}const vc=await compile(vp);check(pixel(vc,120)[0]>250&&pixel(vc,360)[0]>250&&pixel(vc,240)[0]<3,'independent View placement failed');
 const samples=new Float32Array(4800);for(let i=0;i<samples.length;i++)samples[i]=.2*Math.sin(i*2*Math.PI*440/48000);const bytes=encodeWav([samples,samples],48000);p.assets.push({id:'tone',kind:'audio',mime:'audio/wav',sha256:digest(bytes),bytesBase64:b64(bytes),externalRef:null});p.audio.push({id:'event',asset:'tone',start:0,sourceIn:0,sourceOut:.1,rate:1,gain:.5,pan:0});const c=await compile(p),sb3=await exportSB3(c),loaded=await importSB3(sb3.bytes);check(loaded.sounds.length===1,'audio not preserved');check(loaded.lists.AB_TIME[0]===0,'zero checkpoint missing');check(digest(loaded.sounds[0].bytes)===digest(c.sounds[0].bytes),'premix bytes changed');return {timing:'PDF-F08 pass',uiTempoAnchor:'pass',mobileTimingUI:'pass',isolatedAlpha:center[0],mask:'pass',warp:'pass',views:'pass',audioBytes:loaded.sounds[0].bytes.length};
 }));}finally{await browser.close()}
