import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage();await page.goto('http://127.0.0.1:5173/IntroGenerator/');await page.waitForFunction(()=>window.__IG,{timeout:60000});
 console.log(await page.evaluate(async()=>{
 const {makeProject,node,addNode,solid}=await import('/IntroGenerator/src/model.js');const {compile}=await import('/IntroGenerator/src/compiler.js');const {Runtime}=await import('/IntroGenerator/src/runtime.js');const {exportSB3,importSB3}=await import('/IntroGenerator/src/scratch.js');const {encodeWav}=await import('/IntroGenerator/src/audio.js');const {b64,digest}=await import('/IntroGenerator/src/assets.js');
 const check=(x,m)=>{if(!x)throw Error(m)}, project=()=>{const p=makeProject();p.duration=.1;p.background=[0,0,0,1];return p}, rectangle=(p,parent)=>{const n=node('shape');n.data.shape='rectangle';n.data.params.width=100;n.data.params.height=100;n.data.paint=solid([1,1,1,1]);addNode(p,n,parent);return n}, pixel=(c,x=240,y=180)=>{const canvas=document.createElement('canvas');canvas.width=480;canvas.height=360;new Runtime(c).draw(canvas,0);return canvas.getContext('2d').getImageData(x,y,1,1).data};
 const a=project(),g=node('group');g.opacityMode='isolated';g.opacity=.5;addNode(a,g);rectangle(a,g.id);rectangle(a,g.id);const ac=await compile(a),center=pixel(ac);check(Math.abs(center[0]-128)<=2,'isolated alpha applied per child: '+center[0]);
 const p=project(),target=rectangle(p),mask=node('shape','mask',null);mask.data.shape='rectangle';mask.data.params.width=50;mask.data.params.height=100;mask.transform.position[0]=25;p.nodes.push(mask);p.definitions.push(mask.id);target.effects=[{id:'maskFx',kind:'mask',source:mask.id,mode:'alpha',invert:false,feather:0}];const mc=await compile(p);check(pixel(mc,215)[0]<3&&pixel(mc,265)[0]>250,'mask coordinate/alpha mismatch');
 target.effects=[{id:'warpFx',kind:'warp',quad:[[-60,-50],[40,-30],[60,50],[-40,30]],sourceRect:[-50,-50,100,100]}];const wc=await compile(p);check(pixel(wc)[0]>250,'warp center missing');check(pixel(wc,320)[0]<3,'warp outside quad filled');
 const samples=new Float32Array(4800);for(let i=0;i<samples.length;i++)samples[i]=.2*Math.sin(i*2*Math.PI*440/48000);const bytes=encodeWav([samples,samples],48000);p.assets.push({id:'tone',kind:'audio',mime:'audio/wav',sha256:digest(bytes),bytesBase64:b64(bytes),externalRef:null});p.audio.push({id:'event',asset:'tone',start:0,sourceIn:0,sourceOut:.1,rate:1,gain:.5,pan:0});const c=await compile(p),sb3=await exportSB3(c),loaded=await importSB3(sb3.bytes);check(loaded.sounds.length===1,'audio not preserved');check(loaded.lists.AB_TIME[0]===0,'zero checkpoint missing');check(digest(loaded.sounds[0].bytes)===digest(c.sounds[0].bytes),'premix bytes changed');return {isolatedAlpha:center[0],mask:'pass',warp:'pass',audioBytes:loaded.sounds[0].bytes.length};
 }));}finally{await browser.close()}
