import {chromium} from '@playwright/test';
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{const page=await browser.newPage();await page.goto('http://127.0.0.1:5173/IntroGenerator/');await page.waitForFunction(()=>window.__IG,{timeout:60000});
console.log(await page.evaluate(async()=>{
 const {makeProject,node,addNode,animate,solid,constant}=await import('/IntroGenerator/src/model.js'),{AuthorEvaluator}=await import('/IntroGenerator/src/author.js'),{AssetStore}=await import('/IntroGenerator/src/assets.js');
 const project=()=>{const p=makeProject();p.duration=1;p.assets=structuredClone(__IG.state.p.assets);return p},author=p=>new AuthorEvaluator(p,new AssetStore(p)),ok=(x,m)=>{if(!x)throw Error(m)},close=(a,b)=>Math.abs(a-b)<1e-5;
 const p=project(),template=node('shape','template',null);template.data.shape='rectangle';template.data.params.width=4;template.data.params.height=10;p.nodes.push(template);p.definitions.push(template.id);const repeat=node('repeater');repeat.data.template=template.id;repeat.data.count=repeat.data.maxCount=4;repeat.data.delay=.05;repeat.data.rotationStep=0;animate(p,repeat.data,'radius',[[0,0,'linear'],[1,100,'linear']]);addNode(p,repeat);const leaves=author(p).frame(.2);ok(leaves.length===4&&leaves.every(x=>close(Math.hypot(x.m[4],x.m[5]),20)),'repeater delay changed placement time');
 repeat.data.mode='lattice';repeat.data.maxCount=1024;repeat.transform.rotation=45;const tiled=author(p).frame(.2);ok(tiled.length>40,'lattice did not cover rotated viewport');
 const c=project(),group=node('group');group.transform.position[0]=30;addNode(c,group);const path=node('path');path.data.bezier.points=[[-100,0],[100,0]];path.transform.position[0]=50;addNode(c,path,group.id);const follower=node('follower');follower.data.path=path.id;follower.data.u=.5;addNode(c,follower);const follow=author(c).frame(.5).find(x=>x.nodeId===follower.id);ok(close(follow.m[4],80),'follower lost path parent transform');
 path.data.ribbon={widthCurve:'particleAlpha',alphaCurve:'particleScale',spacingPx:10};const ribbon=author(c).frame(.5).filter(x=>x.nodeId===path.id);ok(ribbon.length===20,'Ribbon did not sample arc length');const compiled=await __IG.compile(c);ok(compiled.report.commands>1,'Ribbon compile missing');
 const d=project(),parent=node('group');parent.time.rate=2;addNode(d,parent);const emitter=node('group');animate(d,emitter.transform.position,0,[[0,0,'linear'],[2,20,'linear']]);addNode(d,emitter,parent.id);const particle=node('particle');particle.data.emitter=emitter.id;particle.data.rate=0;particle.data.bursts=[{time:.5,count:1}];particle.data.radialLaunch=null;particle.data.velocity=[constant(4),constant(0),constant(0)];addNode(d,particle,parent.id);const evaluator=author(d),a=evaluator.frame(.5).find(x=>x.nodeId===particle.id);ok(close(a.m[4],7),'particle birth ignored parent time scale: '+a.m[4]);evaluator.frame(.8);ok(JSON.stringify(a)===JSON.stringify(evaluator.frame(.5).find(x=>x.nodeId===particle.id)),'particle seek changed state');
 particle.data.bursts=[];animate(d,particle.data,'rate',[[0,0,'linear'],[2,8,'linear']]);const emitted=author(d).frame(.5).filter(x=>x.nodeId===particle.id);ok(emitted.length===2,'animated emission rate integral mismatch: '+emitted.length);
 return {repeaterTime:'pass',lattice:tiled.length,pathParent:'pass',ribbon:ribbon.length,particleParentTime:'pass',particleSeek:'pass',animatedRate:'pass'};
}));
// The new menu paths must create valid, compilable Source objects.
for(const type of ['follower','trail','view','instance']){await page.locator('#add-type').selectOption(type);await page.locator('#add').click();await page.waitForFunction(()=>__IG.state.compiledRevision===__IG.state.revision,{timeout:90000});await page.locator('#undo').click();await page.waitForFunction(()=>__IG.state.compiledRevision===__IG.state.revision,{timeout:90000})}
console.log('new node controls: pass');
}finally{await browser.close()}
