import {particleLeaves} from './particles.js';
import {ribbonLeaves,decorationLeaves} from './path-style.js';
import {repeatInstances} from './repeater.js';
import {textLeaves} from './text-layout.js';
import {sampleBezier,catmullCubics,trimPath,pathMetrics,atLength} from './paths.js';
import {svgPlan,groupPlan,effectPlan} from './render-plan.js';
import {inverse} from './math.js';
import {I,mul,trs,point,clamp,mod,lerpKeys,bezier,samplePath,random,vdc,rad,hex,beats} from './math.js';
import {shapeGeometry,paintSVG,escape} from './assets.js';
export class AuthorEvaluator{
 constructor(p,assets){this.p=p;this.assets=assets;this.nodes=new Map(p.nodes.map(n=>[n.id,n]));this.exps=new Map(p.expressions.map(e=>[e.id,e]));this.tracks=new Map(p.tracks.map(e=>[e.id,e]));this.cache=new Map();this.warnings=new Set();this.validate()}
 validate(){let roots=[this.p.root,...this.p.definitions],seen=new Set(),active=new Set(),stack=roots.map(id=>[id,false]);while(stack.length){let [id,exit]=stack.pop();if(exit){active.delete(id);seen.add(id);continue}if(active.has(id))throw Error('階層が循環しています');if(seen.has(id))continue;let n=this.nodes.get(id);if(!n)throw Error('Node参照がありません: '+id);active.add(id);stack.push([id,true]);let deps=[...n.children];if(n.type==='repeater'||n.type==='scatter')deps.push(n.data.template);if(n.type==='instance')deps.push(n.data.definition);if(n.type==='trail')deps.push(n.data.source);if(n.type==='view')deps.push(n.data.worldRoot,...[n.data.backgroundRoot,n.data.overlayRoot].filter(Boolean));deps.push(...n.effects.filter(e=>e.kind==='mask').map(e=>e.source));for(let c of deps)stack.push([c,false])}}

 value(v,c,depth=0){if(typeof v==='number')return v;if(depth>100)throw Error('式の参照が深すぎます');let e=this.exps.get(v?.expr);if(!e)throw Error('Expression参照がありません');let f=x=>this.value(x,c,depth+1),a=e.args?.map(f);let r;if(e.op==='input'){if(!(e.name in c))throw Error('この場所では使えない入力: '+e.name);r=c[e.name]}else if(e.op==='track'){let tr=this.tracks.get(e.track);r=lerpKeys(tr.keys,f(e.time),tr.default)}else if(e.op==='seeded')r=random(e.seed,e.tag+':'+f(e.instance));else {r=({add:()=>a[0]+a[1],sub:()=>a[0]-a[1],mul:()=>a[0]*a[1],div:()=>a[0]/a[1],min:()=>Math.min(...a),max:()=>Math.max(...a),pow:()=>a[0]**a[1],modp:()=>mod(a[0],a[1]),sin:()=>Math.sin(rad(a[0])),cos:()=>Math.cos(rad(a[0])),abs:()=>Math.abs(a[0]),floor:()=>Math.floor(a[0]),sqrt:()=>Math.sqrt(a[0]),atan2:()=>Math.atan2(...a)*180/Math.PI,lt:()=>+(a[0]<a[1]),le:()=>+(a[0]<=a[1]),eq:()=>+(a[0]===a[1]),select:()=>a[0]?a[1]:a[2]})[e.op]?.()}if(!Number.isFinite(r)||Math.abs(r)>1e100)throw Error('数値の範囲外です: '+e.id);return r}
 time(n,parent,c){if(parent<n.time.start||parent>=n.time.end)return null;let q=(parent-n.time.start)*n.time.rate+n.time.offset,d=n.time.duration;if(n.time.wrap==='loop')q=mod(q,d);if(n.time.wrap==='pingpong'){q=mod(q,d*2);if(q>d)q=2*d-q}if(n.time.wrap==='clamp')q=clamp(q,0,d);return n.time.remap===null?q:this.value(n.time.remap,{...c,localTime:q})}
 local(n,c){let e=x=>this.value(x,c),tr=n.transform;return trs(...tr.position.slice(0,2).map(e),...tr.scale.map(e),e(tr.rotation),...tr.anchor.map(e))}
 contextAt(id,t,rootTime=t){let chain=[],n=this.nodes.get(id);while(n){chain.push(n);n=this.nodes.get(n.parent)}let c={masterTime:t,localTime:rootTime,index:0,count:1,age:t,normalizedAge:0,birthTime:0},m=I,z=0;for(n of chain.reverse()){let q=this.time(n,c.localTime,c);if(q===null)return null;c={...c,localTime:q};m=mul(m,this.local(n,c));z+=this.value(n.transform.position[2],c)}return {c,m,z}}
 camera(t,id=null,rootTime=t){const viewCameras=new Set(this.p.nodes.filter(n=>n.type==='view').map(n=>n.data.camera));let n=id?this.nodes.get(id):this.p.nodes.find(n=>n.type==='camera'&&n.enabled&&!viewCameras.has(n.id));if(!n)return null;let r=this.contextAt(n.id,t,rootTime);if(!r)return null;let e=x=>this.value(x,r.c);return {x:r.m[4]+e(n.data.shakeX),y:r.m[5]+e(n.data.shakeY),z:r.z,roll:Math.atan2(r.m[1],r.m[0])*180/Math.PI+e(n.data.shakeRoll),zoom:e(n.data.zoom),focal:e(n.data.focal),near:n.data.near,far:n.data.far,perspective:n.data.projection==='perspective'}}
 project(leaf,t){if(leaf.space==='screen')return leaf;let c=this.camera(t,leaf.cameraId,leaf.cameraRootTime??t);if(!c)return leaf;let d=leaf.z-c.z;if(c.zoom<=0||c.perspective&&(d<c.near||d>c.far))return {...leaf,alpha:0};let k=c.zoom*(c.perspective?c.focal/d:1),m=mul(trs(0,0,k,k,-c.roll),trs(-c.x,-c.y));return {...leaf,m:mul(m,leaf.m),space:'screen'}}
 distribution(d,tag){let u=random(this.p.seed,tag);if(d.kind==='constant')return d.value;if(d.kind==='uniform')return d.min+(d.max-d.min)*u;return clamp(d.mean+d.sigma*Math.sqrt(-2*Math.log(Math.max(1e-12,u)))*Math.cos(2*Math.PI*random(this.p.seed,tag+'v')),d.min,d.max)}
 path(n,c){const e=x=>this.value(x,c),error=this.p.profile.curveErrorPx,max=this.p.profile.maxSamples;let pts=[];if(n.data.bezier)pts=sampleBezier(n.data.bezier.points.map(p=>p.map(e)),error,max);else{const cubics=n.data.spline?catmullCubics(n.data.spline.points.map(p=>p.map(e)),n.data.closed):n.data.segments.map(s=>[s.p0,s.p1,s.p2,s.p3].map(p=>p.map(e)));for(const c of cubics){const samples=sampleBezier(c,error,max);pts.push(...(pts.length?samples.slice(1):samples))}}if(n.data.closed&&pts.length&&Math.hypot(pts[0][0]-pts.at(-1)[0],pts[0][1]-pts.at(-1)[1])>1e-8)pts.push(pts[0]);return pts}
 text(n,c){return textLeaves(this,n,c)}
 image(asset,width,height){let a=this.p.assets.find(a=>a.id===asset);if(!a?.bytesBase64)throw Error('素材がありません: '+asset);return {body:`<g transform="scale(1 -1)"><image x="${-width/2}" y="${-height/2}" width="${width}" height="${height}" href="data:${escape(a.mime)};base64,${a.bytesBase64}"/></g>`,bounds:[-width/2,-height/2,width,height],needsRaster:true}}
 decorate(l,n,cc,t,history,cameraTime){const e=x=>this.value(x,cc);let copies=[l];for(let eff of n.effects){if(eff.kind==='trim'){continue}if(eff.kind==='symmetry'){let center=eff.center.map(e),flip=eff.mode==='x'?[1,-1]:eff.mode==='y'?[-1,1]:[-1,-1],fm=trs(...center,...flip,0,...center);let cp={...l,key:l.key+'/mirror',m:eff.space==='local'?mul(l.m,fm):mul(fm,l.m)};if(!eff.transformContent){cp.m=[...l.m.slice(0,4),cp.m[4],cp.m[5]]}copies.push(cp);continue}if(eff.kind==='temporalEcho'||eff.kind==='motionBlur'){if(!history)continue;let duration=eff.kind==='motionBlur'?e(eff.shutterSeconds):e(eff.duration);if(eff.unit==='beats')duration=beats(this.p.tempo,duration);const count=eff.kind==='motionBlur'?Math.min(12,eff.samples):8;if(duration>0){for(let j=1;j<=count;j++){let past=t-duration*j/count;if(past<0)continue;let ct=eff.camera==='current'?t:past,cacheKey=`echo:${past}:${ct}`,pastFrame=this.cache.get(cacheKey);if(!pastFrame){pastFrame=this.frame(past,false,ct);this.cache.set(cacheKey,pastFrame);if(this.cache.size>48)this.cache.delete(this.cache.keys().next().value)}let sample=pastFrame.find(x=>x.key===l.key);if(sample){let strength=eff.kind==='motionBlur'?1/count:e(eff.opacity)*(1-j/(count+1));let cp={...sample,key:l.key+'/echo'+j,order:l.order+'/0echo'+(count-j),alpha:sample.alpha*strength};let softness=eff.softness?e(eff.softness):0;if(softness>0){let pad=softness*3+2;if(cp.plan){cp.plan=effectPlan(cp.plan,{kind:'blur',sigma:softness});cp.bounds=cp.plan.bounds}else cp.body=`<defs><filter id="echo"><feGaussianBlur stdDeviation="${softness}"/></filter></defs><g filter="url(#echo)">${cp.body}</g>`;cp.bounds=[cp.bounds[0]-pad,cp.bounds[1]-pad,cp.bounds[2]+2*pad,cp.bounds[3]+2*pad];cp.needsRaster=!cp.plan}copies.unshift(cp)}}}if(eff.kind==='temporalEcho'&&!eff.includeBase)copies=copies.filter(x=>x!==l);l.order+='/1base';continue}
 if(['blur','glow','shadow','extrude','mask','warp','flash','color'].includes(eff.kind)){
 const params={...eff};for(const key of ['sigma','spread','feather','hue','brightness'])if(eff[key]!==undefined)params[key]=e(eff[key]);for(const key of ['offset','rgba'])if(eff[key])params[key]=eff[key].map(e);if(eff.quad)params.quad=eff.quad.map(p=>p.map(e));
 if(eff.kind==='mask'){const target=this.project(l,cameraTime),inv=inverse(target.m);if(!inv)continue;const mask=this.frame(t,history,cameraTime,eff.source);params.mask=groupPlan(mask.map(x=>({plan:x.plan||svgPlan(x.body,x.bounds),m:mul(inv,x.m),alpha:x.alpha,blend:x.blend||'sourceOver'})));params.matrix=I}
 if(eff.kind==='shadow'){const shadows=copies.map(cp=>{const plan=effectPlan(cp.plan||svgPlan(cp.body,cp.bounds),{...params,includeBase:false});return {...cp,plan,body:'',bounds:plan.bounds,key:cp.key+'/shadow'+eff.id,order:cp.order+'/0shadow',pass:'shadow',needsRaster:false}});copies.forEach(cp=>cp.order+='/1base');copies.unshift(...shadows);continue}
 for(const cp of copies){cp.plan=effectPlan(cp.plan||svgPlan(cp.body,cp.bounds),params);cp.bounds=cp.plan.bounds;cp.needsRaster=false;cp.body=''}
 }}return copies.map(copy=>this.project(copy,cameraTime));}
 frame(t,history=true,cameraTime=t,rootId=this.p.root,options={}){let out=[],c={masterTime:t,localTime:t,index:0,count:1,age:t,normalizedAge:0,birthTime:0};const parent=rootId!==this.p.root&&this.nodes.get(rootId)?.parent?this.contextAt(this.nodes.get(rootId).parent,t):null;let stack=[{id:rootId,c:options.localTime!==undefined?{...c,localTime:options.localTime}:(parent?.c||c),m:parent?.m||I,z:parent?.z||0,alpha:1,space:options.forceScreen?'screen':'world',key:'r',order:'0',cameraId:options.cameraId,cameraRootTime:options.localTime,overrides:options.overrides||[]}],steps=0;
 while(stack.length){if(++steps>20000)throw Error('要素数が出力予算を超えています');let job=stack.pop();if(job.reorder){const f=job.reorder,children=out.splice(f.start);children.sort((a,b)=>f.mode==='shadow'?((a.pass==='shadow'?0:1)-(b.pass==='shadow'?0:1)||a.order.localeCompare(b.order)):(a.key.split('/i').at(-1).replace(/^\d+/, '').localeCompare(b.key.split('/i').at(-1).replace(/^\d+/, ''))||a.order.localeCompare(b.order)));children.forEach((x,i)=>x.order=f.order+'.'+String(i).padStart(7,'0'));out.push(...children);continue}if(job.finalize){const f=job.finalize,children=out.splice(f.start),inv=inverse(f.projected.m);if(!inv)continue;const plan=groupPlan(children.map(x=>({plan:x.plan||svgPlan(x.body,x.bounds),m:mul(inv,x.m),alpha:x.alpha,blend:x.blend||'sourceOver'})));let leaf={key:f.key+'/group',nodeId:f.n.id,order:f.order,m:f.projected.m,z:f.z,alpha:f.opacity,space:'screen',body:'',plan,bounds:plan.bounds,blend:f.n.blend};if(f.n.type==='composition'&&f.n.data.clip){leaf.plan=effectPlan(plan,{kind:'clip',rect:[-f.n.data.width/2,-f.n.data.height/2,f.n.data.width,f.n.data.height]});leaf.bounds=leaf.plan.bounds}out.push(...this.decorate(leaf,f.n,f.c,t,history,cameraTime));continue}let n=this.nodes.get(job.id);if(!n||!n.enabled)continue;if(job.overrides?.some(x=>x.target===n.id)){n=structuredClone(n);for(const o of job.overrides.filter(x=>x.target===n.id)){const keys=o.property.split('.');if(keys.some(k=>['__proto__','prototype','constructor'].includes(k)))throw Error('Overrideの参照が不正です');const last=keys.pop(),target=keys.reduce((x,k)=>x?.[k],n);if(!target||!(last in target))throw Error('Override先がありません');target[last]=o.value}}let q=this.time(n,job.c.localTime,job.c);if(q===null)continue;let cc={...job.c,localTime:q},e=x=>this.value(x,cc),m=mul(job.m,this.local(n,cc)),z=job.z+e(n.transform.position[2]),alpha=job.alpha*clamp(e(n.opacity)),space=n.space==='inherit'?job.space:n.space;let common={c:cc,m,z,alpha,space,key:job.key+'/'+n.id,order:job.order,cameraId:job.cameraId,cameraRootTime:job.cameraRootTime,overrides:job.overrides,colorOffset:job.colorOffset};if(!alpha)continue;
 const push=(id,extra={})=>stack.push({id,...common,...extra});
 if(['group','composition','instance'].includes(n.type)){
 const isolate=n.opacityMode==='isolated'||n.effects.length||n.blend!=='sourceOver'||n.type==='composition'&&n.data.clip;
 if(isolate){stack.push({finalize:{n,start:out.length,projected:this.project({m,z,space,cameraId:job.cameraId,cameraRootTime:job.cameraRootTime},cameraTime),opacity:alpha,c:cc,key:common.key,order:job.order,z}});common.alpha=1}
 if(n.data.passOrder?.[0]==='shadow')stack.push({reorder:{start:out.length,order:job.order,mode:'shadow'}});
 const ids=n.type==='instance'?[n.data.definition]:n.children;if(n.type==='instance')common.overrides=[...(job.overrides||[]),...n.data.overrides];
 for(let i=ids.length-1;i>=0;i--)push(ids[i],{order:job.order+'.'+String(i).padStart(5,'0')});continue}
 if(n.type==='view'){
 const d=n.data,parts=[],center=trs(d.viewport[0]+d.viewport[2]/2,d.viewport[1]+d.viewport[3]/2);
 for(const [id,screen] of [[d.backgroundRoot,true],[d.worldRoot,false],[d.overlayRoot,true]])if(id){const children=this.frame(t,history,cameraTime,id,{localTime:q,cameraId:d.camera,forceScreen:screen,depth:!screen&&d.sort==='depth'});for(const x of children)parts.push({plan:x.plan||svgPlan(x.body,x.bounds),m:mul(center,x.m),alpha:x.alpha,blend:x.blend||'sourceOver'})}
 let plan=groupPlan(parts);if(d.clip)plan=effectPlan(plan,{kind:'clip',rect:d.viewport});const leaf={key:common.key+'/view',nodeId:n.id,order:job.order,plan,body:'',bounds:plan.bounds,m,z,alpha,space,blend:n.blend,cameraId:job.cameraId,cameraRootTime:job.cameraRootTime};out.push(...this.decorate(leaf,n,cc,t,history,cameraTime));continue}
 if(n.type==='camera')continue;
 if(n.type==='repeater'||n.type==='scatter'){const instances=repeatInstances(this,n,cc,m,z,space,cameraTime,job.cameraId,job.cameraRootTime);if(n.data.order==='templateMajor')stack.push({reorder:{start:out.length,order:job.order,mode:'template'}});for(const instance of instances.reverse())push(n.data.template,{c:instance.c,m:instance.m,alpha:alpha*instance.alpha,colorOffset:instance.colorOffset.map((v,i)=>v+(job.colorOffset?.[i]||0)),key:common.key+'/'+instance.key,order:job.order+'.'+String(instance.index).padStart(5,'0')});continue}
 let leaves=[];
 if(n.type==='shape')leaves=[{...shapeGeometry(n,e),m:I,alpha:1,suffix:'shape'}];
 else if(n.type==='text')leaves=this.text(n,cc);
 else if(n.type==='image')leaves=[{...this.image(n.data.asset,e(n.data.width),e(n.data.height)),m:I,alpha:1,suffix:'image'}];
 else if(n.type==='clip'){let k=0;while(k+1<n.data.times.length&&n.data.times[k+1]<=q)k++;let im=this.image(n.data.assets[k],120,120);leaves=[{...im,m:I,alpha:1,suffix:'clip'}]}
 else if(n.type==='path'){let pts=this.path(n,cc),a=e(n.data.trimStart),b=e(n.data.trimEnd),wrap=false;for(const ef of n.effects)if(ef.kind==='trim'){a=e(ef.from);b=e(ef.to);wrap=ef.wrap}const chunks=trimPath(pts,a,b,n.data.closed,wrap);if(!chunks.length)continue;const cut=chunks.flat(),d=n.data,stroke=d.stroke,paint=paintSVG(stroke.paint,e),w=Math.max(0,e(stroke.width)),xs=cut.map(p=>p[0]),ys=cut.map(p=>p[1]);let body=`${paint.defs}<path d="${chunks.map(chunk=>chunk.map((p,i)=>`${i?'L':'M'}${p.join(',')}`).join(' ')).join(' ')}" ${paint.attrs.replaceAll('fill','stroke')} fill="none" stroke-width="${w}" stroke-linecap="${stroke.cap}" stroke-linejoin="${stroke.join}"/>`;
 const bounds=[Math.min(...xs)-w-4,Math.min(...ys)-w-4,Math.max(...xs)-Math.min(...xs)+2*w+8,Math.max(...ys)-Math.min(...ys)+2*w+8];
 if(d.fill){const fp=paintSVG(d.fill,e);leaves.push({body:fp.defs+`<path d="${pts.map((p,i)=>`${i?'L':'M'}${p.join(',')}`).join(' ')}Z" ${fp.attrs}/>`,bounds,m:I,alpha:1,suffix:'fill'})}
 if(stroke.enabled&&w>0&&!d.ribbon)leaves.push({body,bounds,m:I,alpha:1,suffix:'path',penPath:n.effects.every(e=>e.kind==='trim')&&stroke.paint.kind==='solid'&&stroke.cap==='round'&&stroke.join==='round'?{chunks,width:w,rgba:stroke.paint.rgba.map(e),space:stroke.space}:null});
 if(d.ribbon&&stroke.enabled&&w>0)leaves.push(...ribbonLeaves(this,n,cc,chunks));leaves.push(...decorationLeaves(this,n,cc,chunks));
 }
 else if(n.type==='follower'){const path=this.nodes.get(n.data.path),pc=path&&this.contextAt(path.id,t);if(!pc)continue;const r=samplePath(this.path(path,pc.c),e(n.data.u)),location=point(pc.m,r),tangent=point([...pc.m.slice(0,4),0,0],r.slice(2)),angle=e(n.data.rotationOffset)+(n.data.orient?Math.atan2(tangent[1],tangent[0])*180/Math.PI:0);leaves=[{...this.image(n.data.asset,12,12),m:mul(trs(...location,1,1,angle),this.local(n,cc)),z:pc.z+e(n.transform.position[2]),alpha:1,suffix:'follow',absolute:true}]}
 else if(n.type==='trail'){const d=n.data,source=this.nodes.get(d.source);if(!source)throw Error('Trailの対象がありません');const count=Math.min(d.count,this.p.profile.maxDraws),duration=e(d.duration),pathNode=source.type==='follower'?this.nodes.get(source.data.path):source.type==='path'?source:null;
 for(let j=count-1;j>=0;j--){const f=count<=1?0:j/(count-1),when=d.mode==='temporal'?t-duration*f:t,sc=lerpKeys(this.tracks.get(d.widthCurve)?.keys||[],f,this.tracks.get(d.widthCurve)?.default??1),al=lerpKeys(this.tracks.get(d.alphaCurve)?.keys||[],f,this.tracks.get(d.alphaCurve)?.default??1);let location;
 if(pathNode){const context=this.contextAt(pathNode.id,when);if(!context)continue;let u=source.type==='follower'?this.value(source.data.u,this.contextAt(source.id,when)?.c||context.c):1;if(d.mode==='shapeFollow')u-=duration*f;const pos=samplePath(this.path(pathNode,context.c),u);location=point(context.m,pos)}else{const context=this.contextAt(source.id,when);if(!context)continue;location=[context.m[4],context.m[5]]}
 leaves.push({...this.image(d.asset,12,12),m:trs(...location,sc,sc),alpha:al,suffix:'trail'+j,absolute:true})}}
 else if(n.type==='particle')leaves=particleLeaves(this,n,cc,space,job.cameraId,job.cameraRootTime);
 else throw Error(`${n.name}: ${n.type}はこの版では未対応です`);
 if(n.type==='text'&&(n.effects.length||n.opacityMode==='isolated')){const plan=groupPlan(leaves.map(x=>({plan:x.plan||svgPlan(x.body,x.bounds),m:x.m,alpha:x.alpha,blend:'sourceOver'})));leaves=[{plan,body:'',bounds:plan.bounds,m:I,alpha:1,suffix:'text'}]}
 for(let leaf of leaves){if(job.colorOffset?.some(v=>v!==0)){leaf.plan=effectPlan(leaf.plan||svgPlan(leaf.body,leaf.bounds),{kind:'rgbShift',offset:job.colorOffset});leaf.body='';leaf.penPath=null}let l={...leaf,key:common.key+'/'+leaf.suffix,nodeId:n.id,order:job.order+'.'+leaf.suffix,m:leaf.absolute?leaf.m:mul(m,leaf.m),z:leaf.z??z,alpha:alpha*leaf.alpha,space:options.forceScreen?'screen':(leaf.space||space),blend:n.blend,cameraId:job.cameraId,cameraRootTime:job.cameraRootTime};out.push(...this.decorate(l,n,cc,t,history,cameraTime));}
 }
 out.sort((a,b)=>(options.depth?(b.z-a.z):0)||a.order.localeCompare(b.order));for(let i=0;i<out.length;i++)if(out[i].blend&&out[i].blend!=='sourceOver'){const prefix=out.splice(0,i+1),plan=groupPlan(prefix.map(x=>({plan:x.plan||svgPlan(x.body,x.bounds),m:x.m,alpha:x.alpha,blend:x.blend||'sourceOver'})));out.unshift({key:prefix.at(-1).key+'/blend',nodeId:prefix.at(-1).nodeId,order:prefix.at(-1).order,m:I,z:0,alpha:1,space:'screen',body:'',plan,bounds:plan.bounds});i=0}return out
 }
}
