import {b64,utf8,loadImage,hashObject} from './assets.js';
import {I,point,mul,clamp} from './math.js';
const cache=new Map();
export const svgPlan=(body,bounds)=>({kind:'svg',body,bounds});
export function transformedBounds(b,m){const ps=[[b[0],b[1]],[b[0]+b[2],b[1]],[b[0],b[1]+b[3]],[b[0]+b[2],b[1]+b[3]]].map(p=>point(m,p)),x=ps.map(p=>p[0]),y=ps.map(p=>p[1]);return [Math.min(...x),Math.min(...y),Math.max(...x)-Math.min(...x),Math.max(...y)-Math.min(...y)]}
export function unionBounds(all){if(!all.length)return [0,0,1,1];const x=Math.min(...all.map(b=>b[0])),y=Math.min(...all.map(b=>b[1]));return [x,y,Math.max(1,Math.max(...all.map(b=>b[0]+b[2]))-x),Math.max(1,Math.max(...all.map(b=>b[1]+b[3]))-y)]}
export function groupPlan(children,bounds){return {kind:'group',children,bounds:bounds||unionBounds(children.map(c=>transformedBounds(c.plan.bounds,c.m)))}}
export function effectPlan(source,e){let bounds=[...source.bounds];const pad=Math.max(0,e.sigma||0)*3+Math.abs(e.spread||0)+Math.max(...(e.offset||[0,0]).map(Math.abs))+2;if(['blur','shadow','glow','extrude'].includes(e.kind))bounds=[bounds[0]-pad,bounds[1]-pad,bounds[2]+2*pad,bounds[3]+2*pad];if(e.kind==='warp')bounds=unionBounds(e.quad.map(p=>[...p,0,0]));return {kind:'effect',source,e,bounds}}
function surface(bounds){const b=[...bounds],scale=2;b[2]=Math.max(.5,Math.ceil(b[2]*scale)/scale);b[3]=Math.max(.5,Math.ceil(b[3]*scale)/scale);if(b[2]>4096||b[3]>4096)throw Error('局所合成が4096pxを超えます');const canvas=document.createElement('canvas');canvas.width=Math.ceil(b[2]*scale);canvas.height=Math.ceil(b[3]*scale);return {canvas,bounds:b,scale}}
function context(s){const ctx=s.canvas.getContext('2d',{willReadFrequently:true});ctx.setTransform(s.scale,0,0,-s.scale,-s.bounds[0]*s.scale,(s.bounds[1]+s.bounds[3])*s.scale);return ctx}
function draw(ctx,s,m=I,alpha=1,blend='source-over'){ctx.save();ctx.transform(...m);ctx.globalAlpha=clamp(alpha);ctx.globalCompositeOperation=blend==='sourceOver'?'source-over':blend==='add'?'lighter':blend;ctx.scale(1,-1);ctx.drawImage(s.canvas,s.bounds[0],-s.bounds[1]-s.bounds[3],s.bounds[2],s.bounds[3]);ctx.restore()}
// Homography from a unit square to the destination quad, solved without a 3D renderer.
function homography(q){const src=[[0,0],[1,0],[1,1],[0,1]],rows=[];for(let i=0;i<4;i++){const [u,v]=src[i],[x,y]=q[i];rows.push([u,v,1,0,0,0,-x*u,-x*v,x],[0,0,0,u,v,1,-y*u,-y*v,y])}for(let k=0;k<8;k++){let best=k;for(let i=k+1;i<8;i++)if(Math.abs(rows[i][k])>Math.abs(rows[best][k]))best=i;[rows[k],rows[best]]=[rows[best],rows[k]];if(Math.abs(rows[k][k])<1e-10)throw Error('Warpの四隅が退化しています');const d=rows[k][k];for(let j=k;j<=8;j++)rows[k][j]/=d;for(let i=0;i<8;i++)if(i!==k){const d=rows[i][k];for(let j=k;j<=8;j++)rows[i][j]-=d*rows[k][j]}}return rows.map(r=>r[8])}
async function render(plan){const out=surface(plan.bounds),ctx=context(out);if(plan.kind==='svg'){const [x,y,w,h]=plan.bounds;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><g transform="translate(${-x} ${y+h}) scale(1 -1)">${plan.body}</g></svg>`;const image=await loadImage('data:image/svg+xml;base64,'+b64(utf8(svg)));ctx.save();ctx.scale(1,-1);ctx.drawImage(image,x,-y-h,w,h);ctx.restore();return out}
 if(plan.kind==='group'){for(const child of plan.children)draw(ctx,await renderPlan(child.plan),child.m,child.alpha,child.blend);return out}
 const src=await renderPlan(plan.source),e=plan.e;
 if(e.kind==='warp'){const h=homography(e.quad),input=src.canvas.getContext('2d').getImageData(0,0,src.canvas.width,src.canvas.height),dst=ctx.createImageData(out.canvas.width,out.canvas.height),r=e.sourceRect;
  for(let j=0;j<out.canvas.height;j++)for(let i=0;i<out.canvas.width;i++){const x=out.bounds[0]+(i+.5)/2,y=out.bounds[1]+out.bounds[3]-(j+.5)/2,a=h[0]-x*h[6],b=h[1]-x*h[7],c=x-h[2],d=h[3]-y*h[6],f=h[4]-y*h[7],g=y-h[5],det=a*f-b*d;if(Math.abs(det)<1e-10)continue;const u=(c*f-b*g)/det,v=(a*g-c*d)/det;if(u<0||u>1||v<0||v>1)continue;const sx=(r[0]+u*r[2]-src.bounds[0])*2-.5,sy=(src.bounds[1]+src.bounds[3]-(r[1]+v*r[3]))*2-.5,ix=Math.floor(sx),iy=Math.floor(sy),fx=sx-ix,fy=sy-iy;let alpha=0,rgb=[0,0,0];for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++){if(ix+dx<0||iy+dy<0||ix+dx>=input.width||iy+dy>=input.height)continue;const k=((iy+dy)*input.width+ix+dx)*4,weight=(dx?fx:1-fx)*(dy?fy:1-fy)*input.data[k+3]/255;alpha+=weight;for(let c=0;c<3;c++)rgb[c]+=weight*input.data[k+c]}const k=(j*dst.width+i)*4;for(let c=0;c<3;c++)dst.data[k+c]=alpha?rgb[c]/alpha:0;dst.data[k+3]=alpha*255}ctx.putImageData(dst,0,0);return out}
 if(e.kind==='mask'){draw(ctx,src);const ms=surface(out.bounds),mc=context(ms);draw(mc,await renderPlan(e.mask),e.matrix||I);if(e.feather>0){const blurred=surface(out.bounds),bc=context(blurred);bc.filter=`blur(${e.feather*2}px)`;draw(bc,ms);ms.canvas=blurred.canvas}const mask=ms.canvas.getContext('2d').getImageData(0,0,ms.canvas.width,ms.canvas.height),pixels=ctx.getImageData(0,0,out.canvas.width,out.canvas.height);for(let i=0;i<pixels.data.length;i+=4){const a=mask.data[i+3]/255*(e.mode==='luma'?(mask.data[i]*.2126+mask.data[i+1]*.7152+mask.data[i+2]*.0722)/255:1);pixels.data[i+3]*=e.invert?1-a:a}ctx.putImageData(pixels,0,0);return out}
 if(e.kind==='clip'){ctx.save();ctx.beginPath();ctx.rect(...e.rect);ctx.clip();draw(ctx,src);ctx.restore();return out}
 if(e.kind==='blur'){ctx.filter=`blur(${Math.max(0,e.sigma)*2}px)`;draw(ctx,src);return out}
 if(['shadow','glow','extrude'].includes(e.kind)){const tinted=surface(src.bounds),tc=context(tinted);draw(tc,src);tc.globalCompositeOperation='source-in';tc.fillStyle=`rgba(${e.rgba.slice(0,3).map(x=>clamp(x)*255).join(',')},${clamp(e.rgba[3])})`;tc.fillRect(...tinted.bounds);const steps=e.kind==='extrude'?Math.min(512,e.steps):1;ctx.filter=`blur(${Math.max(0,e.sigma||0)*2}px)`;for(let i=steps;i>=1;i--){const k=e.kind==='extrude'?i/Math.max(1,steps):1;draw(ctx,tinted,[1,0,0,1,e.offset[0]*k,e.offset[1]*k],1,e.blend||'sourceOver')}ctx.filter='none';if(e.includeBase!==false)draw(ctx,src);return out}
 draw(ctx,src);if(e.kind==='flash'){ctx.globalCompositeOperation='source-atop';ctx.fillStyle=`rgba(${e.rgba.slice(0,3).map(x=>clamp(x)*255).join(',')},${clamp(e.rgba[3])})`;ctx.fillRect(...out.bounds)}return out;
}
export function renderPlan(plan){const key=hashObject(plan);if(!cache.has(key)){const p=render(plan);cache.set(key,p);p.catch(()=>cache.delete(key));if(cache.size>128)cache.delete(cache.keys().next().value)}return cache.get(key)}
