import {coloredImage} from './colors.js';
import {mul,trs,point,clamp,rad,samplePath,bezier} from './math.js';
import {loadImage} from './assets.js';
export class Runtime{
 constructor(compiled){this.data=compiled;this.L=compiled.lists;this.assets=compiled.assets;this.hit=[];this.entries=compiled.entries||[]}
 track(id,t){const l=this.L,i=id-1,count=l.T_COUNT[i],first=l.T_FIRST[i]-1;if(!count)return l.T_DEFAULT[i];let a=first,b=first+count;while(a<b){let m=(a+b)>>1;if(l.K_TIME[m]<=t)a=m+1;else b=m}let k=Math.max(first,a-1);if(k>=first+count-1)return l.K_VALUE[k];let u=clamp((t-l.K_TIME[k])/(l.K_TIME[k+1]-l.K_TIME[k]));let kind=l.E_KIND[l.K_EASE[k]-1];if(kind===0)u=0;return l.K_VALUE[k]+(l.K_VALUE[k+1]-l.K_VALUE[k])*u}
 program(id,t,index=0,particle=0){let l=this.L,p=id-1,r=new Float64Array(l.P_REGS[p]+1);for(let pc=l.P_FIRST[p]-1,end=pc+l.P_COUNT[p];pc<end;pc++){let op=l.O_CODE[pc],d=l.O_DST[pc],imm=l.O_IMM[pc],args=l.OA_SLOT.slice(l.O_FIRST[pc]-1,l.O_FIRST[pc]-1+l.O_COUNT[pc]),a=args.map(i=>r[i]),v;
 switch(op){case 0:v=imm;break;case 1:v=[t,index,particle][imm];break;case 4:v=a[0];break;case 5:v=a[0]+a[1];break;case 6:v=a[0]-a[1];break;case 7:v=a[0]*a[1];break;case 8:v=a[0]/a[1];break;case 9:v=Math.min(...a);break;case 10:v=Math.max(...a);break;case 11:v=a[0]**a[1];break;case 12:v=Math.abs(a[0]);break;case 13:v=Math.floor(a[0]);break;case 14:v=Math.sqrt(a[0]);break;case 15:v=+Math.sin(rad(a[0])).toFixed(10);break;case 16:v=+Math.cos(rad(a[0])).toFixed(10);break;case 17:v=Math.atan2(a[0],a[1])*180/Math.PI;break;case 18:v=((a[0]%a[1])+a[1])%a[1];break;case 19:v=+(a[0]<a[1]);break;case 20:v=+(a[0]<=a[1]);break;case 21:v=+(a[0]===a[1]);break;case 22:v=a[0]?a[1]:a[2];break;case 23:v=this.track(imm,a[0]);break;case 24:r.set(trs(...a),d);continue;case 25:r.set(mul([...r.slice(args[0],args[0]+6)],[...r.slice(args[1],args[1]+6)]),d);continue;case 26:r.set(point([...r.slice(args[0],args[0]+6)],a.slice(1)),d);continue;default:throw Error('未対応Opcode: '+op)}if(!Number.isFinite(v))throw Error('Runtime数値エラー');r[d]=v}return [...r.slice(l.P_OUTPUT[p],l.P_OUTPUT[p]+l.P_OUTCOUNT[p])]}
 prepare(t){const l=this.L,h=l.IG_HEADER;t=clamp(t,0,h[19]);t=Math.floor(t*h[21]+1e-9)/h[21];let dl=[];for(let c=0;c<l.C_KIND.length;c++){if(t<l.C_START[c]||t>=l.C_END[c])continue;for(let d=l.C_FIRST[c]-1;d<l.C_FIRST[c]-1+l.C_COUNT[c];d++){let v=this.program(l.D_PROGRAM[d],t);if(!v[20]||v[7]<=0)continue;const prim=l.D_PRIM[d];let asset=v[12]||l.D_ASSET[d];if(prim===1&&!this.assets[asset-1])throw Error('素材参照エラー');dl.push({v,asset,prim,nodeId:this.entries[c]?.nodeId})}}return dl}
 draw(canvas,t){let ctx=canvas.getContext('2d'),h=this.L.IG_HEADER,w=canvas.width,hh=canvas.height,ratio=Math.min(w/480,hh/360),fit=h[5];ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.filter='none';ctx.fillStyle='#'+h[6].toString(16).padStart(6,'0');ctx.fillRect(0,0,w,hh);this.hit=[];for(let d of this.prepare(t)){let v=d.v;if(d.prim===2){const sc=ratio*fit;ctx.setTransform(sc,0,0,-sc,w/2,hh/2);ctx.globalAlpha=clamp(v[7]);ctx.filter='none';ctx.lineWidth=v[8];ctx.strokeStyle='#'+Math.round(v[9]).toString(16).padStart(6,'0');ctx.lineCap='round';ctx.beginPath();ctx.moveTo(v[16],v[17]);ctx.lineTo(v[18],v[19]);ctx.stroke();this.hit.push({nodeId:d.nodeId,x:w/2+sc*(v[16]+v[18])/2,y:hh/2-sc*(v[17]+v[19])/2,radius:Math.max(10,Math.hypot(v[18]-v[16],v[19]-v[17])*sc/2)});continue}let a=this.assets[d.asset-1];if(!a.image)continue;let sc=ratio*fit;ctx.setTransform(sc*v[0],-sc*v[1],-sc*v[2],sc*v[3],w/2+sc*v[4],hh/2-sc*v[5]);ctx.globalAlpha=clamp(v[7]);ctx.filter='none';let res=a.res||1;ctx.drawImage(coloredImage(a,v[10],v[11]),-a.cx/res,-a.cy/res,a.width,a.height);this.hit.push({nodeId:d.nodeId,x:w/2+sc*v[4],y:hh/2-sc*v[5],radius:Math.max(a.width,a.height)*Math.hypot(v[0],v[1])*sc/2})}ctx.setTransform(1,0,0,1,0,0);ctx.filter='none';ctx.globalAlpha=1}
}
