import {coloredImage} from './colors.js';
import {trs,clamp,rad} from './math.js';
export class Runtime{
 constructor(compiled){this.data=compiled;this.L=compiled.lists;this.assets=compiled.assets;this.hit=[];this.entries=compiled.entries||[];this.regs=[]}
 track(id,t){const l=this.L,i=id-1,count=l.T_COUNT[i],first=l.T_FIRST[i]-1;if(!count)return l.T_DEFAULT[i];let a=first,b=first+count;while(a<b){let m=(a+b)>>1;if(l.K_TIME[m]<=t)a=m+1;else b=m}let k=Math.max(first,a-1);if(k>=first+count-1)return l.K_VALUE[k];let u=clamp((t-l.K_TIME[k])/(l.K_TIME[k+1]-l.K_TIME[k]));let kind=l.E_KIND[l.K_EASE[k]-1];if(kind===0)u=0;return l.K_VALUE[k]+(l.K_VALUE[k+1]-l.K_VALUE[k])*u}
 program(id,t,index=0,particle=0){const l=this.L,p=id-1,size=l.P_REGS[p]+1;let r=this.regs[p];if(!r||r.length!==size)this.regs[p]=r=new Float64Array(size);else r.fill(0);for(let pc=l.P_FIRST[p]-1,end=pc+l.P_COUNT[p];pc<end;pc++){const op=l.O_CODE[pc],d=l.O_DST[pc],imm=l.O_IMM[pc],first=l.O_FIRST[pc]-1,count=l.O_COUNT[pc],slot=i=>l.OA_SLOT[first+i],arg=i=>r[slot(i)];let v;
 switch(op){case 0:v=imm;break;case 1:v=imm===0?t:imm===1?index:particle;break;case 4:v=arg(0);break;case 5:v=arg(0)+arg(1);break;case 6:v=arg(0)-arg(1);break;case 7:v=arg(0)*arg(1);break;case 8:v=arg(0)/arg(1);break;case 9:{v=Infinity;for(let i=0;i<count;i++)v=Math.min(v,arg(i));break}case 10:{v=-Infinity;for(let i=0;i<count;i++)v=Math.max(v,arg(i));break}case 11:v=arg(0)**arg(1);break;case 12:v=Math.abs(arg(0));break;case 13:v=Math.floor(arg(0));break;case 14:v=Math.sqrt(arg(0));break;case 15:v=+Math.sin(rad(arg(0))).toFixed(10);break;case 16:v=+Math.cos(rad(arg(0))).toFixed(10);break;case 17:v=Math.atan2(arg(0),arg(1))*180/Math.PI;break;case 18:{const a=arg(0),b=arg(1);v=((a%b)+b)%b;break}case 19:v=+(arg(0)<arg(1));break;case 20:v=+(arg(0)<=arg(1));break;case 21:v=+(arg(0)===arg(1));break;case 22:v=arg(0)?arg(1):arg(2);break;case 23:v=this.track(imm,arg(0));break;case 24:{r.set(trs(arg(0),arg(1),arg(2),arg(3),arg(4),arg(5),arg(6)),d);continue}case 25:{const a=slot(0),b=slot(1),a0=r[a],a1=r[a+1],a2=r[a+2],a3=r[a+3],a4=r[a+4],a5=r[a+5],b0=r[b],b1=r[b+1],b2=r[b+2],b3=r[b+3],b4=r[b+4],b5=r[b+5];r[d]=a0*b0+a2*b1;r[d+1]=a1*b0+a3*b1;r[d+2]=a0*b2+a2*b3;r[d+3]=a1*b2+a3*b3;r[d+4]=a0*b4+a2*b5+a4;r[d+5]=a1*b4+a3*b5+a5;continue}case 26:{const m=slot(0),x=arg(1),y=arg(2);r[d]=r[m]*x+r[m+2]*y+r[m+4];r[d+1]=r[m+1]*x+r[m+3]*y+r[m+5];continue}default:throw Error('未対応Opcode: '+op)}if(!Number.isFinite(v))throw Error('Runtime数値エラー');r[d]=v}return Array.from(r.subarray(l.P_OUTPUT[p],l.P_OUTPUT[p]+l.P_OUTCOUNT[p]))}
 prepare(t){const l=this.L,h=l.IG_HEADER;t=clamp(t,0,h[19]);t=Math.floor(t*h[21]+1e-9)/h[21];let dl=[];for(let c=0;c<l.C_KIND.length;c++){if(t<l.C_START[c]||t>=l.C_END[c])continue;for(let d=l.C_FIRST[c]-1;d<l.C_FIRST[c]-1+l.C_COUNT[c];d++){let v=this.program(l.D_PROGRAM[d],t);if(!v[20]||v[7]<=0)continue;const prim=l.D_PRIM[d];let asset=v[12]||l.D_ASSET[d];if(prim===1&&!this.assets[asset-1])throw Error('素材参照エラー');dl.push({v,asset,prim,nodeId:this.entries[c]?.nodeId})}}return dl}
 draw(canvas,t){let ctx=canvas.getContext('2d'),w=canvas.width,hh=canvas.height,ratio=Math.min(w/480,hh/360),fit=this.L.IG_HEADER[5];ctx.setTransform(1,0,0,1,0,0);ctx.globalAlpha=1;ctx.filter='none';ctx.fillStyle='#'+this.L.IG_HEADER[6].toString(16).padStart(6,'0');ctx.fillRect(0,0,w,hh);this.hit=[];for(let d of this.prepare(t)){let v=d.v;if(this.drag?.ids.has(d.nodeId)){const [dx,dy]=this.drag.offset;v[4]+=dx;v[5]+=dy;v[16]+=dx;v[17]+=dy;v[18]+=dx;v[19]+=dy}if(d.prim===2){const sc=ratio*fit;ctx.setTransform(sc,0,0,-sc,w/2,hh/2);ctx.globalAlpha=clamp(v[7]);ctx.filter='none';ctx.lineWidth=v[8];ctx.strokeStyle='#'+Math.round(v[9]).toString(16).padStart(6,'0');ctx.lineCap='round';ctx.beginPath();ctx.moveTo(v[16],v[17]);ctx.lineTo(v[18],v[19]);ctx.stroke();this.hit.push({nodeId:d.nodeId,x:w/2+sc*(v[16]+v[18])/2,y:hh/2-sc*(v[17]+v[19])/2,radius:Math.max(10,v[8]*sc/2),segment:[[w/2+sc*v[16],hh/2-sc*v[17]],[w/2+sc*v[18],hh/2-sc*v[19]]]});continue}let a=this.assets[d.asset-1];if(!a.image)continue;let sc=ratio*fit;ctx.setTransform(sc*v[0],-sc*v[1],-sc*v[2],sc*v[3],w/2+sc*v[4],hh/2-sc*v[5]);ctx.globalAlpha=clamp(v[7]);ctx.filter='none';let res=a.res||1;ctx.drawImage(coloredImage(a,v[10],v[11]),-a.cx/res,-a.cy/res,a.width,a.height);this.hit.push({nodeId:d.nodeId,x:w/2+sc*v[4],y:hh/2-sc*v[5],radius:Math.max(a.width,a.height)*Math.hypot(v[0],v[1])*sc/2,polygon:[[-a.cx/res,-a.cy/res],[-a.cx/res+a.width,-a.cy/res],[-a.cx/res+a.width,-a.cy/res+a.height],[-a.cx/res,-a.cy/res+a.height]].map(([x,y])=>[w/2+sc*(v[0]*x-v[2]*y+v[4]),hh/2+sc*(-v[1]*x+v[3]*y-v[5])])})}ctx.setTransform(1,0,0,1,0,0);ctx.filter='none';ctx.globalAlpha=1}
}
