import {validateRuntime} from './validate-runtime.js';
import ABI from '../schemas/runtime-abi.json';
import {zipSync,unzipSync,strToU8,strFromU8,gunzipSync} from 'fflate';
import {b64,unb64,utf8,digest,md5hex,hashObject,loadImage} from './assets.js';
const V=n=>({opcode:'data_variable',fields:{VARIABLE:[n,'ig:var:'+n]}});
const arg=n=>({opcode:'argument_reporter_string_number',fields:{VALUE:[n,null]}});
const op=(code,inputs={},fields={})=>({opcode:code,inputs,fields});
const num=(code,a,b)=>op('operator_'+code,{NUM1:a,NUM2:b});
const cmp=(code,a,b)=>op('operator_'+code,{OPERAND1:a,OPERAND2:b});
const math=(name,x)=>op('operator_mathop',{NUM:x},{OPERATOR:[name,null]});
const item=(list,index)=>op('data_itemoflist',{INDEX:index},{LIST:[list,'ig:list:'+list]});
const len=list=>op('data_lengthoflist',{}, {LIST:[list,'ig:list:'+list]});
const set=(name,value)=>op('data_setvariableto',{VALUE:value},{VARIABLE:[name,'ig:var:'+name]});
const change=(name,value)=>op('data_changevariableby',{VALUE:value},{VARIABLE:[name,'ig:var:'+name]});
const put=(list,index,value)=>op('data_replaceitemoflist',{INDEX:index,ITEM:value},{LIST:[list,'ig:list:'+list]});
const repeat=(n,body)=>op('control_repeat',{TIMES:n,SUBSTACK:body});
const iff=(condition,body,otherwise)=>op(otherwise?'control_if_else':'control_if',{CONDITION:condition,SUBSTACK:body,...(otherwise?{SUBSTACK2:otherwise}:{})});
const until=(condition,body)=>op('control_repeat_until',{CONDITION:condition,SUBSTACK:body});
const and=(a,b)=>op('operator_and',{OPERAND1:a,OPERAND2:b});
export function engineBlocks(){let blocks={},counter=0,defs=new Map();const id=()=>`ig:block:${++counter}`;
 function emit(spec,parent=null){let k=id(),b={opcode:spec.opcode,next:null,parent,inputs:{},fields:spec.fields||{},shadow:false,topLevel:false};blocks[k]=b;if(spec.mutation)b.mutation=spec.mutation;for(let [key,value] of Object.entries(spec.inputs||{})){if(Array.isArray(value)){let first=chain(value,k);if(first)b.inputs[key]=[2,first]}else if(value&&typeof value==='object'){let r=emit(value,k);b.inputs[key]=[2,r]}else b.inputs[key]=[1,[typeof value==='number'?4:10,String(value)]]}return k}
 function chain(specs,parent=null){let first=null,prev=null;for(let s of specs){let k=emit(s,prev||parent);if(prev)blocks[prev].next=k;first??=k;prev=k}return first}
 function call(name,values=[]){let d=defs.get(name);return {opcode:'procedures_call',inputs:Object.fromEntries(d.ids.map((k,i)=>[k,values[i]])),mutation:{tagName:'mutation',children:[],proccode:d.code,argumentids:JSON.stringify(d.ids),warp:'true'}}}
 function define(name,names){let code=name+names.map(()=> ' %s').join(''),ids=names.map((_,i)=>'param'+i);defs.set(name,{code,ids,names});return names.map(arg)}
 function body(name,specs){let d=defs.get(name),def=id(),proto=id();blocks[def]={opcode:'procedures_definition',next:null,parent:null,inputs:{custom_block:[1,proto]},fields:{},shadow:false,topLevel:true,x:40,y:counter*5};blocks[proto]={opcode:'procedures_prototype',next:null,parent:def,inputs:{},fields:{},shadow:true,topLevel:false,mutation:{tagName:'mutation',children:[],proccode:d.code,argumentids:JSON.stringify(d.ids),argumentnames:JSON.stringify(d.names),argumentdefaults:JSON.stringify(d.names.map(()=>'')),warp:'true'}};d.names.forEach((n,i)=>{let r=emit(arg(n),proto);blocks[r].shadow=true;blocks[proto].inputs[d.ids[i]]=[1,r]});blocks[def].next=chain(specs,def)}
 define('IG INIT',[]);define('IG RENDER FRAME',[]);let [p,t]=define('IG EVAL PROGRAM',['program','time']);let [track,time,slot]=define('IG EVAL TRACK',['track','time','slot']);define('IG DRAW STAMP',[]);
 body('IG INIT',[op('looks_hide'),op('pen_penUp'),op('sound_stopallsounds'),op('looks_setrotationstyle',{},{}),set('IG_ERROR',0),set('IG_PLAYING',1),set('IG_T',0),set('IG_FRAME',-1),op('data_deletealloflist',{}, {LIST:['M','ig:list:M']}),repeat(64,[op('data_addtolist',{ITEM:0},{LIST:['M','ig:list:M']})])].filter(s=>s.opcode!=='looks_setrotationstyle'));
 body('IG EVAL TRACK',[set('TR_FIRST',item('T_FIRST',track)),set('TR_COUNT',item('T_COUNT',track)),set('TR_VALUE',item('T_DEFAULT',track)),iff(cmp('gt',V('TR_COUNT'),0),[set('TR_LOW',V('TR_FIRST')),set('TR_HIGH',num('add',V('TR_FIRST'),V('TR_COUNT'))),until(op('operator_not',{OPERAND:cmp('lt',V('TR_LOW'),V('TR_HIGH'))}),[set('TR_MID',math('floor',num('divide',num('add',V('TR_LOW'),V('TR_HIGH')),2))),iff(op('operator_not',{OPERAND:cmp('gt',item('K_TIME',V('TR_MID')),time)}),[set('TR_LOW',num('add',V('TR_MID'),1))],[set('TR_HIGH',V('TR_MID'))])]),set('TR_K',num('subtract',V('TR_LOW'),1)),iff(cmp('lt',V('TR_K'),V('TR_FIRST')),[set('TR_K',V('TR_FIRST'))]),set('TR_VALUE',item('K_VALUE',V('TR_K')))]),put('M',slot,V('TR_VALUE'))]);
 body('IG EVAL PROGRAM',[set('EV_PC',item('P_FIRST',p)),set('EV_END',num('add',V('EV_PC'),item('P_COUNT',p))),until(op('operator_not',{OPERAND:cmp('lt',V('EV_PC'),V('EV_END'))}),[set('EV_CODE',item('O_CODE',V('EV_PC'))),set('EV_DST',item('O_DST',V('EV_PC'))),iff(cmp('equals',V('EV_CODE'),0),[put('M',V('EV_DST'),item('O_IMM',V('EV_PC')))], [iff(cmp('equals',V('EV_CODE'),1),[put('M',V('EV_DST'),time)],[iff(cmp('equals',V('EV_CODE'),23),[call('IG EVAL TRACK',[item('O_IMM',V('EV_PC')),item('M',item('OA_SLOT',item('O_FIRST',V('EV_PC')))),V('EV_DST')])],[set('IG_ERROR',10)])])]),change('EV_PC',1)])]);
 const M=i=>item('M',i),H=i=>item('IG_HEADER',i);
 body('IG DRAW STAMP',[set('AD_ASSET',M(13)),iff(cmp('equals',V('AD_ASSET'),0),[set('AD_ASSET',item('D_ASSET',V('DR_D')))]),op('looks_switchcostumeto',{COSTUME:item('A_NAME',V('AD_ASSET'))}),op('looks_cleargraphiceffects'),op('looks_seteffectto',{VALUE:num('multiply',num('subtract',1,M(8)),100)},{EFFECT:['GHOST',null]}),op('looks_seteffectto',{VALUE:M(11)},{EFFECT:['COLOR',null]}),op('looks_seteffectto',{VALUE:M(12)},{EFFECT:['BRIGHTNESS',null]}),set('AD_SCALE',math('sqrt',num('add',num('multiply',M(1),M(1)),num('multiply',M(2),M(2))))),op('looks_setsizeto',{SIZE:num('multiply',num('multiply',100,V('AD_SCALE')),H(6))}),set('AD_ANGLE',0),iff(cmp('equals',M(1),0),[iff(cmp('gt',M(2),0),[set('AD_ANGLE',90)],[iff(cmp('lt',M(2),0),[set('AD_ANGLE',-90)])])],[set('AD_ANGLE',math('atan',num('divide',M(2),M(1)))),iff(cmp('lt',M(1),0),[iff(op('operator_not',{OPERAND:cmp('lt',M(2),0)}),[change('AD_ANGLE',180)],[change('AD_ANGLE',-180)])])]),op('motion_pointindirection',{DIRECTION:num('subtract',90,V('AD_ANGLE'))}),op('motion_gotoxy',{X:num('multiply',M(5),H(6)),Y:num('multiply',M(6),H(6))}),op('pen_stamp')]);
 body('IG RENDER FRAME',[op('pen_clear'),set('DR_C',1),repeat(len('C_KIND'),[iff(and(op('operator_not',{OPERAND:cmp('lt',V('IG_T'),item('C_START',V('DR_C')))}),cmp('lt',V('IG_T'),item('C_END',V('DR_C')))),[set('DR_D',item('C_FIRST',V('DR_C'))),repeat(item('C_COUNT',V('DR_C')),[call('IG EVAL PROGRAM',[item('D_PROGRAM',V('DR_D')),V('IG_T')]),iff(and(cmp('gt',M(21),0),cmp('gt',M(8),0)),[call('IG DRAW STAMP')]),change('DR_D',1)])]),change('DR_C',1)])]);
 let flag=emit(op('event_whenflagclicked'));blocks[flag].topLevel=true;blocks[flag].x=20;blocks[flag].y=20;blocks[flag].next=chain([call('IG INIT'),op('sensing_resettimer'),iff(cmp('gt',len('AB_SOUND'),0),[op('sound_play',{SOUND_MENU:item('AU_NAME',item('AB_SOUND',1))})]),call('IG RENDER FRAME'),until(op('operator_not',{OPERAND:and(cmp('lt',V('IG_T'),H(20)),cmp('equals',V('IG_ERROR'),0))}),[set('IG_T',op('sensing_timer')),iff(cmp('gt',V('IG_T'),H(20)),[set('IG_T',H(20))]),set('IG_CURRENT_FRAME',math('floor',num('multiply',V('IG_T'),H(22)))),iff(op('operator_not',{OPERAND:cmp('equals',V('IG_CURRENT_FRAME'),V('IG_FRAME'))}),[call('IG RENDER FRAME'),set('IG_FRAME',V('IG_CURRENT_FRAME'))]),op('control_wait',{DURATION:.001})]),set('IG_PLAYING',0)],flag);
 return blocks
}
function cleanBlocks(blocks){return Object.fromEntries(Object.entries(blocks).map(([id,b])=>[id,Object.fromEntries(Object.entries(b).filter(([k])=>!['x','y','comment'].includes(k)))]))}
export async function exportSB3(compiled){const l=structuredClone(compiled.lists),blocks=engineBlocks(),assets=compiled.assets,soundAssets=compiled.sounds||[],files={},costumes=assets.map(a=>{let path=a.md5+'.'+a.format;files[path]=a.bytes;return {name:a.name,assetId:a.md5,md5ext:path,dataFormat:a.format,rotationCenterX:a.cx,rotationCenterY:a.cy,bitmapResolution:a.res||1}});let carrier=utf8('<svg xmlns="http://www.w3.org/2000/svg" width="480" height="360"><rect width="480" height="360" fill-opacity="0"/></svg>'),cid=md5hex(carrier);files[cid+'.svg']=carrier;costumes.push({name:'IG_CARRIER',assetId:cid,md5ext:cid+'.svg',dataFormat:'svg',rotationCenterX:240,rotationCenterY:180});
 const sounds=soundAssets.map(a=>{files[a.md5+'.wav']=a.bytes;return {name:a.name,assetId:a.md5,dataFormat:'wav',format:'',rate:a.sampleRate,sampleCount:a.sampleCount,md5ext:a.md5+'.wav'}});
 l.IG_HEADER[16]=hashObject(cleanBlocks(blocks));l.IG_HEADER[17]=hashObject({assets:Object.fromEntries(Object.entries(l).filter(([k])=>k.startsWith('A_'))),costumes:costumes.slice(0,-1)});l.IG_HEADER[15]='';l.IG_HEADER[15]=hashObject({lists:Object.fromEntries(Object.entries(l).filter(([k])=>k!=='IG_SOURCE')),media:[...assets.map(a=>a.hash),...soundAssets.map(a=>a.hash)]});
 let variables={};for(let b of Object.values(blocks))if(b.fields.VARIABLE){let [name,id]=b.fields.VARIABLE;variables[id]=[name,0]}
 let lists=Object.fromEntries(Object.entries(l).map(([n,v])=>['ig:list:'+n,[n,v]]));lists['ig:list:M']=['M',[]];let bg=l.IG_HEADER[6].toString(16).padStart(6,'0'),background=utf8(`<svg xmlns="http://www.w3.org/2000/svg" width="480" height="360"><rect width="480" height="360" fill="#${bg}"/></svg>`),bid=md5hex(background);files[bid+'.svg']=background;
 let project={targets:[{isStage:true,name:'Stage',variables:{},lists:{},broadcasts:{},blocks:{},comments:{},currentCostume:0,costumes:[{assetId:bid,name:'Background',md5ext:bid+'.svg',dataFormat:'svg',rotationCenterX:240,rotationCenterY:180}],sounds:[],volume:100,layerOrder:0,tempo:60,videoTransparency:50,videoState:'on',textToSpeechLanguage:null},{isStage:false,name:'IG_PAINTER',variables,lists,broadcasts:{},blocks,comments:{},currentCostume:costumes.length-1,costumes,sounds,volume:100,layerOrder:1,visible:false,x:0,y:0,size:100,direction:90,draggable:false,rotationStyle:'all around'}],monitors:[],extensions:['pen'],meta:{semver:'3.0.0',vm:'0.2.0',agent:'IntroGenerator 0.1.0'}};files['project.json']=strToU8(JSON.stringify(project));return {bytes:zipSync(files,{level:6}),project,lists:l}}
export async function importSB3(bytes){const zip=unzipSync(new Uint8Array(bytes)),project=JSON.parse(strFromU8(zip['project.json']));const painters=project.targets.filter(t=>t.name==='IG_PAINTER'&&t.lists?.['ig:list:IG_HEADER']);if(painters.length!==1)throw Error('IntroGeneratorのsb3を選んでください');const painter=painters[0],l=Object.fromEntries(Object.values(painter.lists).filter(([n])=>n!=='M').map(([n,a])=>[n,a]));validateRuntime(l);if(l.IG_HEADER[0]!=='IGRT/1.1')throw Error('未対応ABI');if(l.IG_HEADER[16]!==hashObject(cleanBlocks(painter.blocks)))throw Error('Scratchブロックが変更されています');let integrity=structuredClone(l),expected=integrity.IG_HEADER[15];integrity.IG_HEADER[15]='';if(expected!==hashObject({lists:Object.fromEntries(Object.entries(integrity).filter(([k])=>k!=='IG_SOURCE')),media:[...l.A_HASH,...l.AU_SOUND.map(i=>{const c=painter.sounds[i-1];if(!c||!zip[c.md5ext])throw Error('音声参照が不正です');return digest(zip[c.md5ext])})]}))throw Error('Runtime Listsが変更されています');const source=JSON.parse(strFromU8(gunzipSync(unb64(l.IG_SOURCE.join('')))));if(hashObject(source)!==l.IG_HEADER[14])throw Error('編集データが破損しています');const metadata=l.A_COSTUME.map(i=>painter.costumes[i-1]);if(l.IG_HEADER[17]!==hashObject({assets:Object.fromEntries(Object.entries(l).filter(([k])=>k.startsWith('A_'))),costumes:metadata}))throw Error('Costumeの設定が変更されています');const assets=[];for(let i=0;i<l.A_COSTUME.length;i++){let c=painter.costumes[l.A_COSTUME[i]-1];if(!c)throw Error('Costume参照が不正です');let bytes=zip[c.md5ext];if(!bytes||digest(bytes)!==l.A_HASH[i]||c.name!==l.A_NAME[i])throw Error('素材の整合性エラー');let url=`data:image/${c.dataFormat==='svg'?'svg+xml':'png'};base64,${b64(bytes)}`;assets.push({id:i+1,name:c.name,width:l.A_W[i],height:l.A_H[i],cx:l.A_CX[i],cy:l.A_CY[i],res:l.A_RES[i],bytes,format:c.dataFormat,hash:l.A_HASH[i],md5:c.assetId,url,image:await loadImage(url)})}const sounds=l.AU_SOUND.map((n,i)=>{const c=painter.sounds[n-1],bytes=zip[c.md5ext];if(c.name!==l.AU_NAME[i])throw Error('音声名が一致しません');return {name:c.name,bytes,hash:digest(bytes),md5:c.assetId,format:'wav',sampleRate:c.rate,sampleCount:c.sampleCount,duration:l.AU_DURATION[i]}});return {source,lists:l,assets,sounds,abi:'IGRT/1.1',entries:[],report:{frames:Math.ceil(source.duration*source.profile.sampleFPS),fps:source.profile.sampleFPS,commands:l.C_KIND.length,assets:assets.length,warnings:[],mode:'sampled'}}}
