import * as hb from 'harfbuzzjs';
import {unb64,paintSVG,escape,hashObject} from './assets.js';
import {trs,mul,inverse,random} from './math.js';
const fonts=new Map(),shapes=new Map();
function fontFor(p,run,e){const asset=p.assets.find(a=>a.id===run.font);if(!asset)throw Error('Fontがありません: '+run.font);const axes=Object.fromEntries(Object.entries(run.axes).map(([k,v])=>[k,e(v)])),key=asset.sha256+JSON.stringify(axes);if(!fonts.has(key)){const blob=new hb.Blob(unb64(asset.bytesBase64).buffer),face=new hb.Face(blob),font=new hb.Font(face);font.setScale(face.upem,face.upem);font.setVariations(Object.entries(axes).map(([tag,value])=>new hb.Variation(tag,value)));fonts.set(key,{blob,face,font,key})}return fonts.get(key)}
function shape(p,text,run,direction,e){const f=fontFor(p,run,e),features=Object.entries(run.features).map(([tag,value])=>new hb.Feature(tag,Number(value))),key=f.key+text+direction+JSON.stringify(run.features);if(shapes.has(key))return shapes.get(key);const buffer=new hb.Buffer();buffer.addCodePoints([...text].map(c=>c.codePointAt(0)));buffer.guessSegmentProperties();if(direction!=='auto')buffer.setDirection(direction==='rtl'?hb.Direction.RTL:hb.Direction.LTR);if(run.language)buffer.setLanguage(run.language);hb.shape(f.font,buffer,features);const infos=buffer.getGlyphInfos(),positions=buffer.getGlyphPositions(),result=infos.map((info,i)=>{if(info.codepoint===0)throw Error('このFontに含まれない文字です。対応Fontを読み込んでください');return {...info,...positions[i],path:f.font.glyphToPath(info.codepoint),extents:f.font.glyphExtents(info.codepoint),upem:f.face.upem}});shapes.set(key,result);if(shapes.size>1024)shapes.delete(shapes.keys().next().value);return result}
export function textLeaves(author,n,c){const p=author.p,d=n.data,e=v=>author.value(v,c),chars=[...d.text],graphemes=[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(d.text)],cpAt=i=>[...d.text.slice(0,i)].length,gmap=new Map(),wordMap=new Map();let words=0;
 for(let [i,g] of graphemes.entries())for(let j=cpAt(g.index);j<cpAt(g.index+g.segment.length);j++)gmap.set(j,i);
 for(const w of new Intl.Segmenter(undefined,{granularity:'word'}).segment(d.text)){const id=words;if(w.isWordLike)words++;for(let j=cpAt(w.index);j<cpAt(w.index+w.segment.length);j++)wordMap.set(j,id)}
 const runAt=i=>d.runs.find(r=>i>=r.from&&i<r.to)||d.runs.at(-1),lines=[];let start=0;for(let i=0;i<=chars.length;i++)if(i===chars.length||chars[i]==='\n'){lines.push({start,end:i});start=i+1}
 // Word wrapping preserves the original character indices and source runs.
 const measure=(a,b,context)=>{let w=0;for(let i=a;i<b;){const run=runAt(i);let end=i+1;while(end<b&&runAt(end)===run)end++;w+=shape(p,chars.slice(i,end).join(''),run,d.direction,v=>author.value(v,context)).reduce((s,g)=>s+g.xAdvance/g.upem*author.value(run.fontSize,context),0);i=end}return w+Math.max(0,b-a-1)*author.value(d.tracking,context)};
 const box=e(d.boxWidth),layoutContext=d.dynamicReflow?c:{...c,localTime:0};if(box>0){for(let li=0;li<lines.length;li++){const line=lines[li];if(measure(line.start,line.end,layoutContext)<=box)continue;let end=line.start+1,lastSpace=-1;while(end<=line.end&&measure(line.start,end,layoutContext)<=box){if(/\s/u.test(chars[end-1]))lastSpace=end;end++}const split=lastSpace>line.start?lastSpace:Math.max(line.start+1,end-1);if(split<line.end){lines.splice(li,1,{start:line.start,end:split},{start:split,end:line.end})}}}
 const out=[];for(let [li,line] of lines.entries()){let x=0,records=[],segments=[];for(let i=line.start;i<line.end;){const run=runAt(i);let end=i+1;while(end<line.end&&runAt(end)===run)end++;segments.push({start:i,end,run});i=end}if(d.direction==='rtl')segments.reverse();
 for(const seg of segments){const run=seg.run,size=e(run.fontSize),glyphs=shape(p,chars.slice(seg.start,seg.end).join(''),run,d.direction,e);for(let j=0;j<glyphs.length;j++){const g=glyphs[j],scale=size/g.upem,cp=seg.start+g.cluster,advance=g.xAdvance*scale;records.push({...g,cp,grapheme:gmap.get(cp)??cp,word:wordMap.get(cp)??0,x:x+g.xOffset*scale,y:g.yOffset*scale,advance,size,scale});x+=advance;if(j===glyphs.length-1||g.cluster!==glyphs[j+1].cluster)x+=e(d.tracking)}}
 const width=Math.max(0,x-(records.length?e(d.tracking):0)),shift=d.align==='center'?-width/2:d.align==='right'?-width:0,baseline=-li*e(d.lineHeight)-(records[0]?.size||0)*.33,clusters=new Map(),wordBounds=new Map();for(const g of records){const cluster=clusters.get(g.cp)||{left:g.x,right:g.x+g.advance,cy:g.size*.33};cluster.left=Math.min(cluster.left,g.x);cluster.right=Math.max(cluster.right,g.x+g.advance);clusters.set(g.cp,cluster);const w=wordBounds.get(g.word)||{left:g.x,right:g.x+g.advance};w.left=Math.min(w.left,g.x);w.right=Math.max(w.right,g.x+g.advance);wordBounds.set(g.word,w)}
 for(let [gi,g] of records.entries()){const cluster=clusters.get(g.cp),center=[shift+(cluster.left+cluster.right)/2,baseline+cluster.cy],word=wordBounds.get(g.word),wp=[shift+(word.left+word.right)/2,baseline+cluster.cy],lp=[shift+width/2,baseline+cluster.cy];let outer=trs(),char=trs(),alpha=1;
 for(const unit of ['line','word','character'])for(const a of d.animators){const au=['line','word'].includes(a.selector.unit)?a.selector.unit:'character';if(au!==unit)continue;let index=unit==='line'?li:unit==='word'?g.word:g.grapheme;if(a.selector.order==='visual'&&unit==='character')index=gi;if(!a.selector.countWhitespace&&unit==='character'){if(/^\s+$/u.test(graphemes[g.grapheme]?.segment||''))continue;index=graphemes.slice(0,g.grapheme).filter(x=>!/^\s+$/u.test(x.segment)).length}if(index<a.selector.from||index>=a.selector.to)continue;const ac={...c,lineIndex:li,wordIndex:g.word,characterIndex:g.grapheme,localTime:c.localTime-e(a.delay)*index-e(a.randomDelay)*random(a.seed,index)+e(a.phase)};const m=author.local({transform:a.transform},ac);alpha*=author.value(a.opacity,ac);if(unit==='character')char=mul(char,m);else{const pivot=unit==='line'?lp:wp;outer=mul(outer,mul(trs(...pivot),mul(m,trs(-pivot[0],-pivot[1]))))}}
 const m=mul(outer,mul(trs(...center),char)),ox=shift+g.x-center[0],oy=baseline+g.y-center[1],paint=paintSVG(d.paint,e),st=d.stroke,ext=g.extents||{xBearing:0,yBearing:0,width:0,height:0},pad=st.enabled?Math.max(1,e(st.width)):1,bounds=[ox+Math.min(ext.xBearing,ext.xBearing+ext.width)*g.scale-pad,oy+Math.min(ext.yBearing,ext.yBearing+ext.height)*g.scale-pad,Math.max(1,Math.abs(ext.width)*g.scale+2*pad),Math.max(1,Math.abs(ext.height)*g.scale+2*pad)];
 let stroke='';if(st.enabled){const sp=paintSVG(st.paint,e);stroke=sp.attrs.replaceAll('fill','stroke')+` stroke-width="${e(st.width)/g.scale}" stroke-linejoin="${st.join}"`;paint.defs+=sp.defs.replaceAll('paint','strokePaint');stroke=stroke.replaceAll('url(#paint)','url(#strokePaint)')}
 out.push({body:paint.defs+`<g ${paint.attrs}><path transform="translate(${ox} ${oy}) scale(${g.scale})" d="${escape(g.path)}" ${stroke}/></g>`,bounds,m,alpha,suffix:'g'+g.cp+'i'+gi+'l'+li})
 }}return out;
}
